id: P8E30FF75
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG6199
  instance_id: http://purl.bdrc.io/resource/IE1KG6199
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - གསུང་འབུམ། འཇམ་དཔལ་དགྱེས་པའི་རྡོ་རྗེ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P8297
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    6b7ad3da5ad64fb0ac8061177de83046:
      title: པོད ༡་གསུང་འབུམ། འཇམ་དཔལ་དགྱེས་པའི་རྡོ་རྗེ།
      volume_number: 1
      base_file: UT1KG6199_I1KG6234_0000.txt
      reference: http://purl.bdrc.io/resource/VL4744BD9EA38693E6
      image_group: I1KG6234
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG6199
  - http://purl.bdrc.io/resource/MW1KG6199
  ocr_software: Namsel
created_at: '2021-12-22T10:58:01.519951'
last_modified_at: '2021-12-22T10:58:01.519956'
statistics:
  total_words: 52221
  total_non_words: 6391
quality:
  non_words_ratio: 0.12
